### ISSUE TITLE
STEP files for AB_Drive Unit

### ISSUE THREAD

**Issue by patchvara** [Annex-Engineering/Redoubt#8]
Hello,

I am thrilled about the concept of having the belt tensioner integrated inside the drive unit. I was wondering if there is a possibility to obtain the STEP files for the AB_Drive unit? I have some modifications in mind that I would like to implement to meet my specific requirements.

Thank you in advance for your assistance.

**Comment by PapeJelly** [comment]
Full CAD of current status has been released, this should have all the parts you need.
